server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5433/wp_dataanswer

spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=wp-dataanswer

free.plan.tokens=1000
guest.plan.tokens=500
pro.plan.tokens=10000

pro.plan.monthly.price=1.99

saved.chats.limit=5

app.session.timeout-seconds=60

token.session.seconds=14400

services.aggregate.url=http://localhost:7100
services.rag.url=http://localhost:7000
services.llm.url=http://localhost:9999