spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# MinIO Configuration (API port 9000)
minio.url=${MINIO_URL}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket=${MINIO_BUCKET}

# Business Configuration
free.plan.tokens=${FREE_PLAN_TOEKS}
guest.plan.tokens=${GUEST_PLAN_TOKENS}
pro.plan.tokens=${PRO_PLAN_TOKENS}

pro.plan.monthly.price=${PRO_PLAN_MONTHLY_PRICE}

saved.chats.limit=${SAVED_CHATS_LIMIT}

app.session.timeout-seconds=${APP_SESSION_TIMEOUT_SECONDS}

services.aggregate.url=${AGGREGATE_URL}
services.rag.url=${RAG_URL}
services.llm.url=${LLM_SERVICE_URL}