server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5433/wp_dataanswer

spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create

minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=wp-dataanswer

free.plan.day.chat.limit=10
free.plan.request.limit-per-chat=10

pro.plan.monthly.price=1.99
pro.plan.day.chat.limit=100
pro.plan.request.limit-per-chat=20

saved.chats.limit=50

guest.plan.request.limit-per-chat=10

app.session.timeout-seconds=1000

services.aggregate.url=http://localhost:7100
services.rag.url=http://localhost:7000
services.llm.url=http://localhost:9999