from FunctionsStructuredData import *

if __name__ == '__main__':
    jsonFile = [
        {"ClubName": "Barca", "Points": 85, "Year": 2020, "Rank": 1},
        {"ClubName": "Real Madrid", "Points": 78, "Year": 2020, "Rank": 2},
        {"ClubName": "Atletico", "Points": 72, "Year": 2020, "Rank": 3},
        {"ClubName": "Sevilla", "Points": 65, "Year": 2020, "Rank": 4},
        {"ClubName": "Barca", "Points": 91, "Year": 2021, "Rank": 1},
        {"ClubName": "Real Madrid", "Points": 87, "Year": 2021, "Rank": 2},
        {"ClubName": "Atletico", "Points": 80, "Year": 2021, "Rank": 3},
        {"ClubName": "Sevilla", "Points": 70, "Year": 2021, "Rank": 4},
        {"ClubName": "Villarreal", "Points": 58, "Year": 2021, "Rank": 5},
        {"ClubName": "Barca", "Points": 55, "Year": 2022, "Rank": 3},
        {"ClubName": "Real Madrid", "Points": 95, "Year": 2022, "Rank": 1},
        {"ClubName": "Atletico", "Points": 71, "Year": 2022, "Rank": 4},
        {"ClubName": "Sevilla", "Points": 60, "Year": 2022, "Rank": 6},
        {"ClubName": "Villarreal", "Points": 75, "Year": 2022, "Rank": 2},
        {"ClubName": "Real Sociedad", "Points": 62, "Year": 2022, "Rank": 5},
        {"ClubName": "Barca", "Points": 88, "Year": 2023, "Rank": 1},
        {"ClubName": "Real Madrid", "Points": 82, "Year": 2023, "Rank": 2},
        {"ClubName": "Atletico", "Points": 77, "Year": 2023, "Rank": 3},
        {"ClubName": "Real Sociedad", "Points": 71, "Year": 2023, "Rank": 4},
        {"ClubName": "Villarreal", "Points": 55, "Year": 2023, "Rank": 7},
        {"ClubName": "Osasuna", "Points": 53, "Year": 2023, "Rank": 8},
        {"ClubName": "Barca", "Points": 76, "Year": 2019, "Rank": 1},
        {"ClubName": "Real Madrid", "Points": 68, "Year": 2019, "Rank": 2},
        {"ClubName": "Atletico", "Points": 76, "Year": 2019, "Rank": 1},
        {"ClubName": "Sevilla", "Points": 58, "Year": 2019, "Rank": 5},
        {"ClubName": "Valencia", "Points": 61, "Year": 2019, "Rank": 4},
        {"ClubName": "Getafe", "Points": 59, "Year": 2019, "Rank": 5},
        {"ClubName": "Barca", "Points": 45, "Year": 2018, "Rank": 2},
        {"ClubName": "Real Madrid", "Points": 93, "Year": 2018, "Rank": 1},
        {"ClubName": "Atletico", "Points": 69, "Year": 2018, "Rank": 3},
        {"ClubName": "Valencia", "Points": 73, "Year": 2018, "Rank": 2},
        {"ClubName": "Villarreal", "Points": 45, "Year": 2018, "Rank": 7},
        {"ClubName": "Sevilla", "Points": 53, "Year": 2018, "Rank": 5},
        {"ClubName": "Barca", "Points": 99, "Year": 2017, "Rank": 1},
        {"ClubName": "Real Madrid", "Points": 93, "Year": 2017, "Rank": 2},
        {"ClubName": "Atletico", "Points": 78, "Year": 2017, "Rank": 3},
        {"ClubName": "Sevilla", "Points": 72, "Year": 2017, "Rank": 4},
        {"ClubName": "Villarreal", "Points": 63, "Year": 2017, "Rank": 5},
        {"ClubName": "Real Sociedad", "Points": 57, "Year": 2017, "Rank": 6},
        {"ClubName": "Eibar", "Points": 55, "Year": 2017, "Rank": 7},
        {"ClubName": "Barca", "Points": 91, "Year": 2016, "Rank": 1},
        {"ClubName": "Real Madrid", "Points": 90, "Year": 2016, "Rank": 2},
        {"ClubName": "Atletico", "Points": 88, "Year": 2016, "Rank": 3},
        {"ClubName": "Villarreal", "Points": 64, "Year": 2016, "Rank": 4},
        {"ClubName": "Sevilla", "Points": 62, "Year": 2016, "Rank": 5},
        {"ClubName": "Athletic Bilbao", "Points": 55, "Year": 2016, "Rank": 6},
        {"ClubName": "Real Sociedad", "Points": 50, "Year": 2016, "Rank": 7},
        {"ClubName": "Celta Vigo", "Points": 60, "Year": 2016, "Rank": 5},
        {"ClubName": "Barca", "Points": 38, "Year": 2024, "Rank": 4},
        {"ClubName": "Real Madrid", "Points": 95, "Year": 2024, "Rank": 1}
    ]

    print(FunctionAvg(jsonFile, [("ClubName", "Barca", "==")], "Points"))