FROM python:3.12-slim

# prevent buffered i/o
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# needed fo numpy
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    g++ \
    libnuma1 \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

# get vllm version
ENV VLLM_VERSION=0.19.1

# install vllm
RUN pip install https://github.com/vllm-project/vllm/releases/download/v${VLLM_VERSION}/vllm-${VLLM_VERSION}+cpu-cp38-abi3-manylinux_2_35_x86_64.whl --extra-index-url https://download.pytorch.org/whl/cpu

# starting servis
CMD python -m vllm.entrypoints.openai.api_server --model ${MODEL_NAME} --port 8000 --enable-auto-tool-choice --tool-call-parser hermes
