FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    g++ \
    curl \
    libnuma1 \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

ENV VLLM_VERSION=0.19.1

RUN pip install https://github.com/vllm-project/vllm/releases/download/v${VLLM_VERSION}/vllm-${VLLM_VERSION}+cpu-cp38-abi3-manylinux_2_35_x86_64.whl --extra-index-url https://download.pytorch.org/whl/cpu

RUN pip install --force-reinstall \
    "prometheus-fastapi-instrumentator==7.0.0" \
    "fastapi==0.115.12"

COPY patch_routing.py .
RUN python patch_routing.py

CMD python -m vllm.entrypoints.openai.api_server --model ${MODEL_NAME} --port 8000 --enable-auto-tool-choice --tool-call-parser hermes