version: "3.9"

services:
  vllm:
    build:
      context: vllm
      dockerfile: Dockerfile.vllm-cpu
    environment:
      - MODEL_NAME=Qwen/Qwen2.5-0.5B-Instruct
      - VLLM_CPU_OMP_THREADS_BIND=0-7
      - VLLM_CPU_KVCACHE_SPACE=2
      - HF_TOKEN=${HF_TOKEN}
    shm_size: '8gb'
    ports:
      - "8000:8000"
    volumes:
      - huggingface_cache:/root/.cache/huggingface
    networks:
      - services_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 3m
    
  llm-service:
    build:
      context: vllm
    environment:
      - VLLM_URL=http://vllm:8000
      - TOOL_SERVICE_URLS=http://rag-service:7000,http://aggregate-service:7100
    ports:
      - "9999:9999"
    networks:
      - services_net
    depends_on:
      vllm:
        condition: service_healthy
      rag-service:
        condition: service_healthy
      aggregate-service:
        condition: service_healthy


  rag-service:
    build:
      context: RAG
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET=wp-dataanswer
    ports:
      - "7000:7000"
    networks:
      - services_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    depends_on:
      - minio

  aggregate-service:
    build:
      context: AggregationMicroservice
    ports:
      - "7100:7100"
    networks:
      - services_net
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7100/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s 
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wp_dataanswer
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - services_net

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"   # API port (Spring Boot connects here)
      - "9001:9001"   # Web UI port (browser)
    volumes:
      - minio_data:/data
    networks:
      - services_net

  spring-service:
    build:
      context: BackEnd/backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET=wp-dataanswer
      - FREE_PLAN_DAY_CHAT_LIMIT=${FREE_PLAN_DAY_CHAT_LIMIT}
      - FREE_PLAN_REQUEST_LIMIT_PER_CHAT=${FREE_PLAN_REQUEST_LIMIT_PER_CHAT}
      - PRO_PLAN_MONTHLY_PRICE=${PRO_PLAN_MONTHLY_PRICE}
      - PRO_PLAN_DAY_CHAT_LIMIT=${PRO_PLAN_DAY_CHAT_LIMIT}
      - PRO_PLAN_REQUEST_LIMIT_PER_CHAT=${PRO_PLAN_REQUEST_LIMIT_PER_CHAT}
      - SAVED_CHATS_LIMIT=${SAVED_CHATS_LIMIT}
      - GUEST_PLAN_REQUEST_LIMIT_PER_CHAT=${GUEST_PLAN_REQUEST_LIMIT_PER_CHAT}
      - APP_SESSION_TIMEOUT_SECONDS=${APP_SESSION_TIMEOUT_SECONDS}
      - AGGREGATE_URL=http://aggregate-service:7100
      - RAG_URL=http://rag-service:7000
      - LLM_SERVICE_URL=http://llm-service:9999
    ports:
      - "9090:9090"
    networks:
      - services_net
    depends_on:
      - db
      - minio
      - llm-service

networks:
  services_net:
    driver: bridge

volumes:
  huggingface_cache:
  db_data:
  minio_data:
